DROP TABLE IF EXISTS
items, users, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    available BOOLEAN,
    owner_id BIGINT,
    request VARCHAR(1024),
    foreign key (owner_id) references users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    rent_start TIMESTAMP,
    rent_end TIMESTAMP,
    item_id BIGINT not null references items(id),
    booker_id BIGINT not null references users(id),
    status VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    message TEXT,
    item_id BIGINT not null,
    user_id BIGINT not null,
    created TIMESTAMP,
    foreign key (item_id) references items(id),
    foreign key (user_id) references users(id)
);
