DROP TABLE IF EXISTS
items, users, bookings, comments, requests CASCADE;

DROP INDEX IF EXISTS name_description_items;
DROP INDEX IF EXISTS owner_id_items;
DROP INDEX IF EXISTS booker_id_bookings;
DROP INDEX IF EXISTS item_id_bookings;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    available BOOLEAN,
    owner_id BIGINT,
    request_id BIGINT,
    foreign key (owner_id) references users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    rent_start TIMESTAMP,
    rent_end TIMESTAMP,
    item_id BIGINT not null references items(id),
    booker_id BIGINT not null references users(id),
    status VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    message TEXT,
    item_id BIGINT not null,
    user_id BIGINT not null,
    created TIMESTAMP,
    foreign key (item_id) references items(id),
    foreign key (user_id) references users(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description TEXT,
    user_id BIGINT not null,
    created TIMESTAMP,
    foreign key (user_id) references users(id)
);


-- добавил индекс для поиска вещей по описанию и наименованию
-- также в помощь к запросу find by query
CREATE INDEX IF NOT EXISTS name_description_items ON items (name, description);
-- для поиска вещи по владельцу
CREATE INDEX IF NOT EXISTS owner_id_items ON items (owner_id);
-- для поиска бронирований клиента
CREATE INDEX IF NOT EXISTS booker_id_bookings ON bookings (booker_id);
-- для помощи в поиске бронирований по владельцу вещи
CREATE INDEX IF NOT EXISTS item_id_bookings ON bookings (item_id);


